### ISSUE TITLE
no such hash table element: yh

### ISSUE THREAD

**Issue by bjoerntorben** [MoonLiightz/dotfiles#12] opened 2023-01-29 14:40 UTC
### System information

OS: macOS Ventura 13.2
arch: arm64
Package Manager: Homebrew 3.6.20
zsh: 5.9 (arm-apple--darwin-22.1.0)

### Bug description

Error message prompt: /Users/username/.dotfiles/zsh/conf/aliases.zsh:unalias:3: no such hash table element: yh

### Steps to reproduce

1. ./bootstrap.sh all
2. answer all questions with 'Y'
3. Restart terminal

### Expected behavior

No error messages at all.

**Comment by MoonLiightz** [comment] 2023-03-20 11:52
I think the problem is related to your #11 issue because the oh-my-zsh (omz) installation was not successful. yh is an alias created by the omz yarn plugin. But at the same time yh is also this application [andreazorzetto/yh](https://github.com/andreazorzetto/yh). I don't need the yh alias and to avoid conflicts, I removed it. But if the plugin was not installed, this error can occur. I would say that this issue is a duplicate of your previous issue.

**Closed as not planned** 2023-03-20 11:53 UTC
Labels: status: duplicate, type: bug
